### PR TITLE
DLC: The Forgotten Kingdom

### PR DESCRIPTION
**Pull request by TheNasbit**
# General
- [x] Changed Wiki to [remnant.wiki](https://remnant.wiki/) #233
- [x] Option to switch between [Fextralife](https://remnant2.wiki.fextralife.com/) and [remnant.wiki](https://remnant.wiki/)
# DLC: The Awakened King
- [x] Added Leywise and Farlorn Coast as Sections
- [x] Possible fix for Shaed Stone #232
- I did lot of cleanup. Item list for DLC1 should look more structured now.
# DLC: The Forgotten Kingdom
### Traits
- [x] Replaced Resonance with Leech
- [x] Replaced Wayfarer with Chakra
- [x] Resolute
### Archetypes
- [ ] Invoker
### Weapons
- [x] Crystal Staff
- [x] Mirage
- [x] Monolith
- [x] Polygun
- [x] Shovel
- [x] Thorn
- [x] Trinity Crossbow
### Armors
- [x] Battle Gloves
- [x] Battle Helmet
- [x] Battle Shirt
- [x] Battle Slacks
- [x] Bloodless Crown
- [x] Dandy Topper
- [x] Disciple Mantle
- [x] Disciple Greaves
- [x] Disciple Headpiece
- [x] Disciple Vambraces
- [x] Mudtooth's Hat
- [ ] Survivor Mask
- [x] True Crimson Crown
### Rings
- [x] Black Spinel
- [x] Bloodless King's Vow
- [x] Burden of the Mason
- [x] Burden of the Mesmer
- [x] Closed Loop
- [x] Conjurer's Circle
- [x] Dark Sea Armada Crest
- [x] Feathery Binding
- [x] Floodlit Diamond
- [x] Gul Signet
- [x] Kolket Eyelet
- [x] Leaking Gemstone
- [x] Mark of the Destroyer
- [x] Matriarch's Ring
- [x] Pan War Band
- [x] Rally Band
- [x] Ravager's Bargain
- [x] Ring of Ordnance
- [x] Ring of Spirits
- [x] Sealed Resin Loop
- [x] Soul Feast
- [x] Tear of Lydusa
- [x] Thalos Eyelet
- [x] Token of Favor
### Amulets
- [x] Beads of the Valorous
- [x] Cervine Keepsake
- [x] Echo of the Forest
- [x] Fragrant Thorn
- [x] Magnifying Glass
- [x] Moon Stone
- [x] Profane Soul Stone
- [x] Reed of the Vaunnt
- [x] Soul Stone
- [x] Stoneshaper's Chisel
- [x] Worn Dog Tags
- [x] Zero Divide
### Mods
- [x] Abrasive Rounds
- [x] Flying Bomb Trap
- [x] Heatwave
### Mutators
- [x] Battle Mage
- [x] Far-Sighted
- [x] Gladiator
- [x] Near-Sighted
- [x] Pressure Point
- [x] Searing Wounds
- [x] Spellweaver
- [x] Thousand Cuts
### Relics
- [x] Bloodless Heart
- [x] Profane Heart

### CODE REVIEW

**Comment by TheNasbit** [comment]
Still work in progress

**Comment by MikeFindlay** [comment]
> Still work in progress

I have a bunch of the items you're looking for in the new DLC, but I'm not sure how to convert my save file into a readable format with the full item file path.

**Comment by TheNasbit** [comment]
> > Still work in progress
> 
> I have a bunch of the items you're looking for in the new DLC, but I'm not sure how to convert my save file into a readable format with the full item file path.

You can send the .sav file itself if you want. I have also a items lot too - just had not the time to work on it before the weekend - so just started today.

**Comment by MikeFindlay** [comment]
[save_0.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15140451/save_0.zip)
Here it is. If its a quick explanation and you wouldn't mind sending a quick how-to, I'd enjoy learning. no problem either way tho.

**Comment by Keller0Junge** [comment]
[bakup.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15142966/all.new.items.zip)
this is my latest backup with SaveGuardian, it should contain all new items. Hope it helps :)
*didn't know which of the 2 characters is the right one, so thats why you will find both in the zip file

**Comment by identity7** [comment]
i dont have much, but i might have smth unique [rem.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15144037/rem.zip)



> [bakup.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15142966/all.new.items.zip) this is my latest backup with SaveGuardian, it should contain all new items. Hope it helps :) *didn't know which of the 2 characters is the right one, so thats why you will find both in the zip file

your profile.sav contains all character information(obtained guns/melee/armor/rings/amulets/etc...) for all your save slots. your save_#.sav contains world information(your rolled campaign/adventure/quest items) for each individiual save slot. save_0.sav is for slot 1, save_1.sav is for slot 2, etc...

**Comment by ethaldeman** [comment]
In your initial list, it seems you are missing the new relics, [Profane Heart](https://remnant2.wiki.fextralife.com/Profane+Heart) and [Bloodless Heart](https://remnant2.wiki.fextralife.com/Bloodless+Heart)

**Comment by Frutaa** [comment]
Should I upload a profile.sav that has collected all the new items, or some world save such as save_0.sav that  collect each new item please?

> > > Still work in progress
> > 
> > 
> > I have a bunch of the items you're looking for in the new DLC, but I'm not sure how to convert my save file into a readable format with the full item file path.
> 
> You can send the .sav file itself if you want. I have also a lot items - just had not the time to work on it before the weekend - so just started today.

**Comment by identity7** [comment]
also, if anyone needs it for any reason, i have a save_#.sav with the unrolled DLC oneshot available
[oneshot.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15149947/oneshot.zip)

**Comment by Wuxriff** [comment]
/Game/World_DLC2/Items/Archetypes/Invoker/Engram/Engram_Invoker.Engram_Invoker_C
The last one?

**Comment by ethaldeman** [comment]
According to Fextralife wiki,  [Survivor Mask](https://remnant2.wiki.fextralife.com/Survivor+Mask) is currently unaviable to obtain in game. The remnant.wiki doesn't have a page for it.

**Comment by TheNasbit** [comment]
Big thank to @Keller0Junge for the character-file, and @identity7 for the savegame, both had lot of items my file were missing, and safed lot of time :)

**Comment by grunt000** [comment]
Dark Sea Armada Crest is incorrectly reported as missing.

**Comment by identity7** [comment]
zero divide(n'erud random drop) as well

**Comment by TheNasbit** [comment]
Both Items should be fixed - (not updated pre-release, but in this PR it's fixed now) - thanks.
Let me know if you find more issues.

**Comment by drkrthnblck** [comment]
> Both Items should be fixed - (not updated pre-release (yet), but in this PR it's fixed now) - thanks. Let me know if you find more issues.

How compatible is your PR build with the existing one—does it take existing settings into account, is there a way to safely merge the backed up saves, that kind of thing?

**Comment by identity7** [comment]
> > Both Items should be fixed - (not updated pre-release (yet), but in this PR it's fixed now) - thanks. Let me know if you find more issues.
> 
> How compatible is your PR build with the existing one—does it take existing settings into account, is there a way to safely merge the backed up saves, that kind of thing?

perfectly. old version can be deleted and nothing is changed/lost since RSG doesn't directly manipulate the save files

**Comment by TheNasbit** [comment]
Pushed a [Pre-Release](https://github.com/TheNasbit/RemnantSaveGuardian/releases/tag/DLC2) with the fixes. -

**Comment by KitakamiRei** [comment]
Did a DLC2 adventure run through Yaseha. The Archer's Crest injectable was erronously reported to be in The Twisted Chantry but was actually instead in The Proving Grounds.

**Comment by ethaldeman** [comment]
When loading my save, I am getting the below error.

image
 
My Save it attached. 
[638502770659645341.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15195088/638502770659645341.zip)

**Comment by TheNasbit** [comment]
> When loading my save, I am getting the below error.
> 
> [...]
> 
> My Save is attached. [638502770659645341.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15195088/638502770659645341.zip)

That's super odd, you get a Yaesha Injectable on a N'Erud Adventure in your save game? - Have to dig deeper. Something seems off.



> Did a DLC2 adventure run through Yaseha. The Archer's Crest injectable was erronously reported to be in The Twisted Chantry but was actually instead in The Proving Grounds.

The tool sets the location for injectables to the "parent" location before the injectable - but seems like this is not always the case. Not sure yet how to fix it. It is not an explicit DLC2 problem, can also happen with DLC1 Stuff. Had it in the past some times. But I see if I can fix it. Can not promise it will fixed in this PR, tho.

**Comment by VioletCapybara** [comment]
I'm seeing an injectable (Flute Tower) that does not exist (I don't even have a possible spawning point for it) in a TFK adventure. It does not appear when using the current version of the program.

RSG_dlc2_err

Save is [attached](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15202936/RSG_dlc2_err.zip)

**Comment by m1ndgap** [comment]
I can see my backups from the 1.2.2.0 version, but trying to load them (world only) does nothing: new backup is not created and upon starting the game I just load where I left the game before. Is this intended?

**Comment by xarcoft** [comment]
Tested my save files with PR 1.3.0.0 and loaded successfully but is showing wrong location for some injectables and items.
From my testing couldn't find Magnifying Glass anywhere on Malefic Palace, also Rookery injectable doesn't seem to be right to that location.
image

Also rolled an adventure mode to get 3 items i was missing (Closed Loop, Zero Divide and Ring of Ordnance) but for 2 of them the location was wrong.
image
I actually found Closed Loop on The Hatchery and Zero Divide on Timeless Horizon.
The location for Ring of Ordnance was correct.

Save file is [attached](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/15206633/RSG_Temp.zip)

**Comment by razeedazee** [comment]
Not N'Erud

image

**Comment by razeedazee** [comment]
image

**Comment by razeedazee** [comment]
So i am rerolling the campaign to do something and i see these

image

**Comment by razeedazee** [comment]
I think i understand it, it's whatever the first world is.

image

**Review by Razzmatazzz — APPROVED** [review]
Thanks much for all the work on the PR!

**Comment by TheNasbit** [comment]
> @xarcoft @razeedazee are these problems specific to this new branch and not preset on the current main release?

These problems also appeared after DLC1, but it increased by a lot with the new content. It's mainly because of the parsing of the events, as the "world" is World_DLC1 / World_DLC2, and right now we take the "parent" event (previous events) / location's world.

It worked fine in most cases. Even though problems like those described above already happened sometimes before. The new DLC drastically increased the chance of it. 

I think we have to change a bit of the parsing to fix it. Just replacing World_DLC1 with World_Fae, and World_DLC2 with World_Jungle won't fix it, that is what we had at the beginning of DLC1 adaption, but random drops on other worlds would then be listed as the wrong planet.

**Comment by Razzmatazzz** [comment]
Is this PR ready to go, or does it need some additional tweaking before being merged?

**Comment by TheNasbit** [comment]
> Is this PR ready to go, or does it need some additional tweaking before being merged?

Problems are not because of the added items - IMO an rewrite of the Event parsing exceeds the scope of this PR. I AM working on the problem, but it is more an fundamental problem than problem bound to DLC2.

So yes - it is ready to go. BUT we have to work on the problems in another PR.
The problems happened before - I got them myself in the past before DLC2. So its not "new" with this PR. With the new DLC you will see the problem more often. 

Please do not think I will ignore the problems - I will work on it. But will take some more time.

**Comment by razeedazee** [comment]
bit late but i'll add it, the stuff i encountered was more a cosmetic issue, the functionality was fine for my particular needs, even this https://github.com/Razzmatazzz/RemnantSaveGuardian/pull/236#issuecomment-2091935631

It was mostly working maybe a couple of kinks to iron out.

**Comment by TheNasbit** [comment]
> bit late but i'll add it, the stuff i encountered was more a cosmetic issue, the functionality was fine for my particular needs, even this [#236 (comment)](https://github.com/Razzmatazzz/RemnantSaveGuardian/pull/236#issuecomment-2091935631)
> 
> It was mostly working maybe a couple of kinks to iron out.

@razeedazee 
It is the same issue that we have for a while now, it just happens more often with even more DLC-Contents:
https://github.com/Razzmatazzz/RemnantSaveGuardian/pull/209#issuecomment-1827127426

We need to do some changes to the Event-parsing to fix them

**Pull request merged**
