### PR TITLE
Add known DLC3 items

### PR DESCRIPTION
**Pull request by silvanshade**
This PR adds support for most of the known DLC3 items (except for prisms).

### CODE REVIEW

**Comment by Q-Sharp** [comment]
nice work mate.
@Razzmatazzz

**Comment by silvanshade** [comment]
I've associated most of the new items with their locations but there are a couple of issues:

1. In DLC3 one shot mode, the `DLC3Story` area seems to be detected incorrectly. The associated location for it is detected as `Losomn: Stagnant Manufactury`.
2. In DLC3 one shot mode, the POI is detected as location `N'Erud: Logistics Bridge` with the name `The Custodian`.

I'm assuming those issues are probably due to some special case handling that is no longer quite valid with the new patterns introduced by DLC3. I'll try to figure out how to fix that if someone else doesn't get to it first.

Also, I would think that the new boss area `The Convergence` should show up and that there should be a POI or something associated with the `Prototype` robot. There are several items that would need to have their locations set to those to be more accurate.

**Comment by silvanshade** [comment]
I've added a second commit which attempts to fix the invalid location rendering. In order to do this, I basically added another mapping from "sublocation" back to the associated "world".

This mapping is computed within the loop that loads the `"subLocations"` field from `game.json`, to try and avoid needing to add a bunch of additional data.

It seems to be sufficient to fix the problem for the few error cases I encountered but it may be that a few more locations need to be added (similar to how I have done here) if there are other cases not covered.

I considered just exhaustively adding all known locations for all of the worlds to that mapping but it seemed unnecessary. But that might be a better way to go just to be sure.

**Review by Razzmatazzz — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
