### PR TITLE
DLC1: The Awakened King

### PR DESCRIPTION
**Pull request by TheNasbit**
# DLC1: The Awakened King
Added Items from The Awakened King.

"Look - there are 2 PR for DLC items, but they have just some of the changes... " - Now there are 3 PR for DLC items.
... yeah. Thats my brain in a nutshell.

Added all known items. Fixed reading of DLC-Items. (Since all of them are listed for "World_DLC1" - but the worlds are the existing ones.) 

### Armor
- [x] Crimsom Guard
- [x] Zealot / Ritualist
### Archetypes
- [ ]  Ritualist
  - Ritualist is differently implemented... have to adapt.
#### Melee
- [x] Abyssal Hook
- [x] Ritualist Scythe
- [x] Steel Scythe (Brabus)
- [x] Wrathbringer
#### Hand Gun
- [ ] Anguish
  - No Specific location, you have to travel over all the worlds to obtain, the "Dranception" Event breaks some of the other worlds - so will not shown in the list.
#### Long Gun
- [x] Monarch
- [x] Sparkfire Shotgun
### Traits
- [x] Dark Pact
- [x] Affliction
### Weapon Mods
- [x] Creeping Mist
- [x] Knight Guard
- [x] Ring Of Spears
#### Ranged
- [x] Dreadful
- [x] Fetid Wounds
- [x] Maelstrom
- [x] Prophecy
- [x] Sleeper
#### Melee
- [x] Executor
- [x] Guts
- [x] Tainted Blade
### Amulets
- [x] Birthright Of The Lost
- [x] Brewmasters Cork
- [x] Cost Of Betrayal
- [x] Death-Soaked Idol
- [x] Gift Of Euphoria
- [x] Gift Of Melancholy
- [x] Gift Of The Unbound
- [x] Index Of The Scribe
- [x] Legacy Protocol
- [x] Sinister Totem
- [x] Whispering Marble
### Rings
- [x] Atonement Fold
- [x] Band Of The Fanatic
- [x] Bitter Memento
- [x] Bridge Wardens Crest
- [x] Brawler's Pride
- [x] Burden Of Departed
- [x] Burden Of The Sciolist
- [x] Crimson Dreamstone
- [x] Digested Hog Lure
- [x] Dried Clay Ring
- [x] Elevated Ring
- [x] Jewel Of The Beholden
- [x] Lighthouse Keeper's Ring
- [x] Offering Stone
- [x] Painless Obsidian
- [x] Power Complex
- [x] Ring Of Infinite Damage
- [x] Ring Of The Castaway
- [x] Ring Of The Vain
- [x] Shadow Of Misery
- [x] Shaed Stone
- [x] Soul Shard
- [x] Wood Ring
- [x] Red Ring Of Death
- [x] White Glass Bead
### Merchant
- [x] Leywise (Added to Translation-File, but not listed in World Analyzer yet... We have to adapt the Event Reader more to get NPCs? Or at least the different Areas like Forlorn Coast etc.)
### Relics
- [x] Broken Heart
- [x] Paper Heart
## Other
- DLC Items won't show "World_DLC1", but the World they are in (Yaesha, N'Erud, Losomn), since they all tagged as "World_DLC1" but actually random Drops in all worlds (at least some of them)
- In Debug save-files always safed as .txt in save-folder
- Correct reading of Adventure Mode, since the new Storyline is  now AdventureMode_OTK

### CODE REVIEW

**Comment by TheNasbit** [comment]
image
Thats just TOO much in The One True King... I am looking/working on a way to get this split up.
But that's probably something for another PR

**Comment by TheNasbit** [comment]
Will fix new conflicts

**Comment by Razzmatazzz** [comment]
@TheNasbit Thanks for working on this PR! I haven't been able to look at the PR in great detail, but it appears to target lots of the same items as PRs #182 and #188. We should try to get everybody working on the same page for all this new content so we can avoid duplication of effort as much as possible!

**Comment by TheNasbit** [comment]
Some things broke during merge - working on fix.

**Comment by TheNasbit** [comment]
> Some things broke during merge - working on fix.

Nevermind - just a quotation mark was missing in the json 😅

But add missing traits when I'm already on it.

**Comment by TheNasbit** [comment]
Does someone want to review and merge? It is sitting here for 3 days.

**Review by Razzmatazzz — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
From the PRs list, it looked like there were two tasks left to be finished. Will push out a new release soon.

**Comment by TheNasbit** [comment]
> From the PRs list, it looked like there were two tasks left to be finished. Will push out a new release soon.

Yes two items will not (yet) shown in the list. They will need further changes. Not sure yet.

**Pull request merged**
